spring.application.name=finance-data-processing

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=${JWT_SECRET}

# Access token TTL in milliseconds (default: 10 minutes)
security.jwt.access-ttl-ms=600000
# Refresh token TTL in milliseconds (7 days)
security.jwt.refresh-ttl-ms=604800000

app.session.limit=2